"""Export a trained SAC actor to a plain-JS weights file for the browser game.

GitHub Pages can't run PyTorch, so we ship the *policy* instead of the runtime:
the actor is a tiny MLP (16 -> [256, 256] -> 2), so we dump its weights to
``docs/policy.js`` and re-implement the forward pass in JavaScript (see
``docs/game.js`` ``rlBot``). The deterministic action is ``tanh(mu(h))`` where
``h`` is the ReLU MLP trunk output — matching ``model.predict(deterministic=True)``.

    D:\\Code\\.venv\\Scripts\\python.exe scripts\\export_policy.py --model runs\\sac_final.zip

Keep this in sync with :func:`airhockey.env.build_observation` and
:func:`airhockey.opponents.mirror_state` — the JS port must build the identical
16-d observation in the mirrored (left-attacker) frame.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=str(ROOT / "runs" / "sac_final.zip"))
    ap.add_argument("--out", default=str(ROOT / "docs" / "policy.js"))
    args = ap.parse_args()

    from stable_baselines3 import SAC

    model = SAC.load(args.model, device="cpu")
    sd = model.policy.actor.state_dict()

    def arr(key: str) -> list:
        # Round to float32-ish precision to keep the shipped JS small; the policy
        # is robust to <1e-6 weight perturbations.
        a = np.asarray(sd[key].cpu().numpy(), dtype=np.float64)
        return np.round(a, 6).tolist()

    # latent_pi = [Linear(16,256), ReLU, Linear(256,256), ReLU]; then mu = Linear(256,2).
    # Store weights row-major exactly as PyTorch (shape [out, in]) so JS can do
    # out[i] = bias[i] + sum_j W[i][j] * x[j].
    weights = {
        "obs_dim": int(sd["latent_pi.0.weight"].shape[1]),
        "act_dim": int(sd["mu.weight"].shape[0]),
        "layers": [
            {"w": arr("latent_pi.0.weight"), "b": arr("latent_pi.0.bias"), "act": "relu"},
            {"w": arr("latent_pi.2.weight"), "b": arr("latent_pi.2.bias"), "act": "relu"},
            {"w": arr("mu.weight"), "b": arr("mu.bias"), "act": "tanh"},
        ],
        "source": Path(args.model).name,
    }

    out = Path(args.out)
    payload = json.dumps(weights, separators=(",", ":"))
    out.write_text(
        "/* Auto-generated by scripts/export_policy.py — do not edit by hand.\n"
        f" * Source model: {weights['source']}  |  net: 16 -> [256,256] -> 2 (tanh)\n"
        " * Deterministic SAC actor: action = tanh(mu(relu(W2 relu(W1 obs)))). */\n"
        f"window.RL_POLICY = {payload};\n",
        encoding="utf-8",
    )
    size_kb = out.stat().st_size / 1024
    print(f"wrote {out}  ({size_kb:.0f} KB)  from {weights['source']}")


if __name__ == "__main__":
    main()
